# Generated by Django 5.0.3 on 2024-12-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
